<?php

// === 1. Chargement des fréquences INSEE ===
$frequences = [];
$handle = fopen("nat2022.csv", "r");

fgetcsv($handle, 0, ";"); // saute l’en-tête

while (($data = fgetcsv($handle, 0, ";")) !== FALSE) {
    $genre = trim($data[0]);
    $prenom = trim($data[1]);
    $annee = (int) trim($data[2]);
    $nombre = (int) trim($data[3]);

    if ($annee >= 1900 && $annee <= 2000) {
        if (!isset($frequences[$prenom])) {
            $frequences[$prenom] = 0;
        }
        $frequences[$prenom] += $nombre;
    }
}
fclose($handle);

print("All data imported \n");

// === 2. Chargement du tableau original ===
$prenoms_complet=
[
    '01-01' => ['Clair', 'Fulgence', 'Zdislava'],
    '01-02' => ['Basile', 'Grégoire', 'Séraphin', 'Stéphanie'],
    '01-03' => ['Geneviève'],
    '01-04' => ['Angèle'],
    '01-05' => ['Edouard', 'Emilienne'],
    '01-06' => ['Balthazar', 'Epiphane', 'Fanny', 'Gaspard', 'Melchior', 'Théophanie'],
    '01-07' => ['Aldric', 'Raymond'],
    '01-08' => ['Gudule', 'Lucien'],
    '01-09' => ['Alice', 'Alix', 'Pauline'],
    '01-10' => ['Gonzague', 'Guillaume', 'Léonie'],
    '01-11' => ['Hortense', 'Paulin'],
    '01-12' => ['Marguerite', 'Tanina', 'Tatiana'],
    '01-13' => ['Godefroy', 'Hilaire'],
    '01-14' => ['Nino', 'Odoric'],
    '01-15' => ['Ita', 'Maur', 'Rachel', 'Rémi'],
    '01-16' => ['Bérard', 'Marcel', 'Othon'],
    '01-17' => ['Roseline'],
    '01-18' => ['Priscille', 'Prisque'],
    '01-19' => ['Marius', 'Marthe', 'Pia'],
    '01-20' => ['Fabien', 'Sébastien'],
    '01-21' => ['Agnès', 'Epiphane', 'Oona', 'Safia'],
    '01-22' => ['Laura', 'Timothée', 'Vincent'],
    '01-23' => ['Emérentienne'],
    '01-24' => ['François', 'Paule'],
    '01-25' => ['Ananie', 'Apollos'],
    '01-26' => ['Paule', 'Pauline', 'Timothée', 'Tite'],
    '01-27' => ['Angèle', 'Dévote'],
    '01-28' => ['Charlemagne', 'Thomas'],
    '01-29' => ['Gildas'],
    '01-30' => ['Bathilde', 'Bertille', 'Martine'],
    '01-31' => ['Marcella', 'Marcelle', 'Tobie'],
    '02-01' => ['Ella', 'Luigi'],
    '02-02' => ['Anschaire', 'Blaise', 'Claudine', 'Hadelin'],
    '02-03' => ['Bérénice', 'Vanessa', 'Véronique'],
    '02-04' => ['Agathe', 'Avit'],
    '02-05' => ['Dorothée', 'Gaston', 'Hiba', 'Xénia'],
    '02-06' => ['Audren', 'Eugénie', 'Providence'],
    '02-07' => ['Bakhita', 'Jacqueline', 'Joséphine', 'Zacharie'],
    '02-08' => ['Apolline', 'Miguel'],
    '02-09' => ['Arnaud', 'Scholastique'],
    '02-10' => ['Héloïse', 'Théodora'],
    '02-11' => ['Mélèce', 'Mélisende', 'Ombeline'],
    '02-12' => ['Ange', 'Jourdain', 'Tancrède'],
    '02-13' => ['Cyrille', 'Méthode', 'Valentin'],
    '02-14' => ['Claude', 'Faustin', 'Georgette', 'Onésime'],
    '02-15' => ['Julienne', 'Lucile'],
    '02-16' => ['Alexis', 'Flavien', 'Théodule'],
    '02-17' => ['Bernadette', 'François-Régis', 'Jean-Pierre'],
    '02-18' => ['Gabin', 'Philothée'],
    '02-19' => ['Aimée'],
    '02-20' => ['Pépin', 'Pierre-Damien', 'Sirpa'],
    '02-21' => ['Isabelle'],
    '02-22' => ['Alexandre', 'Polycarpe'],
    '02-23' => ['Ethelbert', 'Modeste'],
    '02-24' => ['Gerland', 'Guerlain', 'Nestor'],
    '02-25' => ['Alexandre'],
    '02-26' => ['Galmier', 'Honorine'],
    '02-27' => ['Auguste', 'Romain'],
    '02-28' => ['Antoine', 'Eugénie', 'Martinien'],
    '03-01' => ['Albin', 'Jonathan'],
    '03-02' => ['Chad', 'Charles'],
    '03-03' => ['Cunégonde', 'Guénolé', 'Gwenolé', 'Marin'],
    '03-04' => ['Casimir', 'Roméo'],
    '03-05' => ['Conon', 'Olive'],
    '03-06' => ['Colette', 'Nicole'],
    '03-07' => ['Félicité', 'Perpétue'],
    '03-08' => ['Humphroy'],
    '03-09' => ['Françoise', 'Romaine'],
    '03-10' => ['Simplice', 'Vivien'],
    '03-11' => ['Rosine'],
    '03-12' => ['Justine', 'Paul-Aurélien', 'Pol', 'Pol-Aurélien'],
    '03-13' => ['Cléandre', 'Léandre', 'Rodrigue', 'Salomon'],
    '03-14' => ['Ève', 'Èvelyne', 'Mathilde'],
    '03-15' => ['Ihsan', 'Louise', 'William'],
    '03-16' => ['Bénédicte', 'Eusébie'],
    '03-17' => ['Gertrude', 'Patrick'],
    '03-18' => ['Cyrille', 'Salvator'],
    '03-19' => ['Joseph', 'Sibylle'],
    '03-20' => ['Alexandra', 'Claudia', 'Herbert'],
    '03-21' => ['Clémence', 'Lupicin'],
    '03-22' => ['Léa', 'Tyliana'],
    '03-23' => ['Rébecca', 'Victorien'],
    '03-24' => ['Catherine', 'Oscar'],
    '03-25' => ['Annonciade', 'Humbert'],
    '03-26' => ['Lara', 'Larissa', 'Ludger'],
    '03-27' => ['Albert', 'Rupert'],
    '03-28' => ['Gontran', 'Jeanne-Marie'],
    '03-29' => ['Archibald', 'Gladys', 'Pasteur'],
    '03-30' => ['Amédée'],
    '03-31' => ['Aldo', 'Benjamin'],
    '04-01' => ['Hugues', 'Ludovic', 'Valéry'],
    '04-02' => ['Alexandrine'],
    '04-03' => ['Richard'],
    '04-04' => ['Alèthe', 'Alex', 'Isidore'],
    '04-05' => ['Irène', 'Julienne', 'Théodora'],
    '04-06' => ['Célestin', 'Perrine', 'Pierrette'],
    '04-07' => ['Ashley', 'Jean Baptiste', 'Marie-Assunta'],
    '04-08' => ['Constance', 'Gauthier', 'Julie'],
    '04-09' => ['Démétrius', 'Dimitri'],
    '04-10' => ['Fulbert', 'Grégoire', 'Térence'],
    '04-11' => ['Stanislas'],
    '04-12' => ['Jules'],
    '04-13' => ['Ida'],
    '04-14' => ['Lambert', 'Lidwine', 'Maxime', 'Valérien'],
    '04-15' => ['Anastasie', 'César', 'Paterne'],
    '04-16' => ['Benoît-Joseph', 'Bernadette', 'Druon'],
    '04-17' => ['Anicet', 'Cheyenne', 'Kateri'],
    '04-18' => ['Parfait'],
    '04-19' => ['Emma'],
    '04-20' => ['Odette', 'Théotime'],
    '04-21' => ['Anselme'],
    '04-22' => ['Alexandre', 'Epipode'],
    '04-23' => ['Georges'],
    '04-24' => ['Fidèle', 'Roy', 'Wilfrid'],
    '04-25' => ['Marc', 'Melle'],
    '04-26' => ['Alda', 'Riquier'],
    '04-27' => ['Amédée', 'Zita'],
    '04-28' => ['Chanel', 'Pierre-Marie', 'Valérie'],
    '04-29' => ['Catherine', 'Sienne'],
    '04-30' => ['Joseph-Benoît', 'Robert'],
    '05-01' => ['Jérémie', 'Joseph'],
    '05-02' => ['Antonin', 'Athanase', 'Boris', 'Kaan', 'Zoé'],
    '05-03' => ['Jacques', 'Philippe'],
    '05-04' => ['Florian', 'Sylvain'],
    '05-05' => ['Judith', 'Michée', 'Nunzio'],
    '05-06' => ['Lucius', 'Marien', 'Prudence'],
    '05-07' => ['Domitille', 'Flavia', 'Gisèle', 'Marie-Louise'],
    '05-08' => ['Arsène', 'Désiré'],
    '05-09' => ['Caroline', 'Marie-Thérèse', 'Pacôme'],
    '05-10' => ['Damien', 'Job', 'Solange'],
    '05-11' => ['Estelle', 'Maïeul', 'Mamert', 'Mayeul'],
    '05-12' => ['Achille', 'Nerea', 'Nérée', 'Pancrace'],
    '05-13' => ['Fatima', 'Nazaré', 'Servais'],
    '05-14' => ['Matthias', 'Pons'],
    '05-15' => ['Denise', 'Primaël'],
    '05-16' => ['Brady', 'Brendan', 'Honoré'],
    '05-17' => ['Pascal'],
    '05-18' => ['Eric'],
    '05-19' => ['Azou', 'Crispin', 'Soën', 'Théophile', 'Yves', 'Yvette'],
    '05-20' => ['Bernardin', 'Lydéric', 'Lydie'],
    '05-21' => ['Constantin'],
    '05-22' => ['Emile', 'Emilie', 'Quitterie', 'Rita'],
    '05-23' => ['Didier', 'Guibert'],
    '05-24' => ['Donatien', 'Rogatien'],
    '05-25' => ['Flavien', 'Salomé', 'Sophie'],
    '05-26' => ['Bérenger'],
    '05-27' => ['Augustin'],
    '05-28' => ['Germain', 'Guilhem', 'Guillaume'],
    '05-29' => ['Bona', 'Géraldine', 'Maximin', 'Ursule'],
    '05-30' => ['Ferdinand', 'Jeanne', 'Lorraine'],
    '05-31' => ['Lise-Marie', 'Marie-Elisabeth', 'Marie-Lise'],
    '06-01' => ['Justin', 'Ronan'],
    '06-02' => ['Alcide', 'Blandine', 'Emilie', 'Pothin'],
    '06-03' => ['Kevin', 'Morand'],
    '06-04' => ['Bréaca', 'Clotilde', 'Marthe', 'Quirin'],
    '06-05' => ['Boniface', 'Igor', 'Sanche'],
    '06-06' => ['Claude', 'Marcellin', 'Norbert'],
    '06-07' => ['Colman', 'Gilbert', 'Marie-Thérèse'],
    '06-08' => ['Davy', 'Godard', 'Médard'],
    '06-09' => ['Ephrem', 'Félicien', 'Prime'],
    '06-10' => ['Diane', 'Foulques', 'Landry'],
    '06-11' => ['Barnabé', 'Yolande'],
    '06-12' => ['Guy'],
    '06-13' => ['Antoine', 'Rambert'],
    '06-14' => ['Elisée', 'Lidwine'],
    '06-15' => ['Bénilde', 'Germaine', 'Landelin', 'Lothaire'],
    '06-16' => ['Aurélien', 'Cyr', 'François-Régis', 'Ismaël', 'Jean-François', 'Julitte', 'Régis'],
    '06-17' => ['Hervé', 'Rainier'],
    '06-18' => ['Amand', 'Hosanna', 'Léonce'],
    '06-19' => ['Déodat', 'Gervais', 'Jude', 'Romuald', 'Thaddée'],
    '06-20' => ['Balthazar', 'Gobain', 'Silvère'],
    '06-21' => ['Gonzague', 'Louis', 'Raoul', 'Rodolphe', 'Rudolf'],
    '06-22' => ['Alban', 'Aubin'],
    '06-23' => ['Etheldrede', 'Paule'],
    '06-24' => ['Jean', 'Jean Baptiste'],
    '06-25' => ['Eléonore', 'Luan', 'Prosper'],
    '06-26' => ['Anthelme', 'Maxence'],
    '06-27' => ['Cyrille', 'Ferdinand', 'Fernand'],
    '06-28' => ['Irénée'],
    '06-29' => ['Paul', 'Pierre', 'Saül', 'Simon', 'Simon-Pierre'],
    '06-30' => ['Ladislas', 'Martial', 'Sloane'],
    '07-01' => ['Aaron', 'Olivier', 'Thierry'],
    '07-02' => ['Colomban', 'Eugénie', 'Martinien'],
    '07-03' => ['Thomas'],
    '07-04' => ['Elisabeth', 'Isabelle'],
    '07-05' => ['Antoine-Marie', 'Zoé'],
    '07-06' => ['Isaïe', 'Maria', 'Marietta'],
    '07-07' => ['Ralph', 'Raoul', 'Roger'],
    '07-08' => ['Aquila', 'Prisca', 'Priscille', 'Thibaud'],
    '07-09' => ['Amandine', 'Andrée', 'Natalie'],
    '07-10' => ['Emmanuel', 'Numa', 'Ulric'],
    '07-11' => ['Benoît'],
    '07-12' => ['Jason', 'Louis', 'Olivier', 'Zélie'],
    '07-13' => ['Clélia', 'Henri', 'Horst'],
    '07-14' => ['Angeline', 'Camille'],
    '07-15' => ['Basile', 'Bonaventure', 'Donald', 'Vladimir'],
    '07-16' => ['Carmel', 'Carmen', 'Elvire', 'Hélier'],
    '07-17' => ['Charlotte', 'Hedwige', 'Livier', 'Marcelline'],
    '07-18' => ['Arnoul', 'Arnould', 'Arnoult', 'Frédéric'],
    '07-19' => ['Arsène', 'Aura', 'Aurea'],
    '07-20' => ['Aurèle', 'Elie'],
    '07-21' => ['Daniel', 'Laurent', 'Victor'],
    '07-22' => ['Madeleine', 'Marie-Madeleine'],
    '07-23' => ['Brigitte', 'Ezéchiel'],
    '07-24' => ['Christine', 'Ségolène'],
    '07-25' => ['Christophe', 'Jacques'],
    '07-26' => ['Anne', 'Joachim'],
    '07-27' => ['Nathalie'],
    '07-28' => ['Nazaire', 'Samson'],
    '07-29' => ['Lazare', 'Loup', 'Marthe', 'Olav'],
    '07-30' => ['Juliette'],
    '07-31' => ['Ignace', 'Loyola'],
    '08-01' => ['Alphonse', 'Alphonse-Marie'],
    '08-02' => ['Julien', 'Pierre-Julien'],
    '08-03' => ['Lydéric', 'Lydie'],
    '08-04' => ['Darcy', 'Jean-Marie', 'Vianney'],
    '08-05' => ['Abel', 'Marie des Neiges', 'Nonna'],
    '08-06' => ['Octavien', 'Sauveur'],
    '08-07' => ['Félicissime', 'Gaétan', 'Sixte'],
    '08-08' => ['Dominique'],
    '08-09' => ['Bénédicte', 'Edith', 'Thérèse', 'Thérèse-Bénédicte'],
    '08-10' => ['Laure', 'Laurent', 'Philomène'],
    '08-11' => ['Claire', 'Suzanne'],
    '08-12' => ['Chantal', 'Jeanne', 'Jeanne-Françoise'],
    '08-13' => ['Hippolyte', 'Radegonde'],
    '08-14' => ['Kolbe', 'Maximilien'],
    '08-15' => ['Assomption', 'Marie'],
    '08-16' => ['Armel', 'Roch'],
    '08-17' => ['Claire'],
    '08-18' => ['Hélène', 'Laëtitia', 'Liesse', 'Marie-Hélène'],
    '08-19' => ['Eudes', 'Géric', 'Guerric', 'Jean-Eudes'],
    '08-20' => ['Bernard', 'Samuel'],
    '08-21' => ['Christophe', 'Yuna'],
    '08-22' => ['Fabrice', 'Fabricien', 'Marie-Reine', 'Reine'],
    '08-23' => ['Eugène', 'Rose', 'Roseline'],
    '08-24' => ['Barthélemy', 'Emilie', 'Nathanaël'],
    '08-25' => ['Louis'],
    '08-26' => ['Césaire'],
    '08-27' => ['Guérin', 'Monique'],
    '08-28' => ['Augustin', 'Vivien'],
    '08-29' => ['Crispin', 'Jean Baptiste', 'Sabine'],
    '08-30' => ['Fantin', 'Fantine', 'Fiacre'],
    '08-31' => ['Aristide', 'Cody', 'Nicodème'],
    '09-01' => ['Gilles', 'Josué'],
    '09-02' => ['Habib', 'Ingrid'],
    '09-03' => ['Grégoire'],
    '09-04' => ['Boniface', 'Moïse', 'Rosalie'],
    '09-05' => ['Bertin', 'Raïssa'],
    '09-06' => ['Bertrand', 'Ève', 'Zacharie'],
    '09-07' => ['Clodoald', 'Reine'],
    '09-08' => ['Adrien', 'Beline', 'Séraphine'],
    '09-09' => ['Alain', 'Frédéric', 'Ozan'],
    '09-10' => ['Aubert', 'Inès'],
    '09-11' => ['Adelphe', 'Jean-Gabriel', 'Vinciane'],
    '09-12' => ['Apollinaire'],
    '09-13' => ['Aimé', 'Marcellin'],
    '09-14' => [''],
    '09-15' => ['Dolorès', 'Roland'],
    '09-16' => ['Edith', 'Ninian'],
    '09-17' => ['Hildegarde', 'Réginald', 'Renaud'],
    '09-18' => ['Maona', 'Océane', 'Richarde'],
    '09-19' => ['Emilie', 'Goëry', 'Marie-Emilie', 'Marien'],
    '09-20' => ['Eusébie', 'Jean-Charles'],
    '09-21' => ['Castor', 'Déborah', 'Jonas', 'Levi', 'Matthieu', 'Mélina'],
    '09-22' => ['Candide', 'Laud', 'Lô', 'Maurice', 'Silvain'],
    '09-23' => ['Constant', 'Lin', 'Line'],
    '09-24' => ['Anatole', 'Mercedes', 'Pacifique', 'Siloé', 'Silouane'],
    '09-25' => ['Aurélie', 'Cléophas', 'Solenne'],
    '09-26' => ['Côme', 'Damien', 'Eusèbe', 'Gédéon', 'Nil'],
    '09-27' => ['Hiltrude', 'Vincent'],
    '09-28' => ['Loucas', 'Lucas', 'Venceslas'],
    '09-29' => ['Gabriel', 'Gaïane', 'Michel', 'Raphaël', 'Rhipsimé'],
    '09-30' => ['Félicie', 'Jérôme', 'Ours'],
    '10-01' => ['Ariel', 'Arielle', 'Mélodie', 'Paësie', 'Romanos', 'Thérèse'],
    '10-02' => ['Ange', 'Léger', 'Ruth'],
    '10-03' => ['Bianca', 'Candide', 'Gérard'],
    '10-04' => ['Aure', 'Capucin', 'Capucine', 'François', 'Paco'],
    '10-05' => ['Faustine', 'Fleur', 'Flora', 'Marie-Faustine'],
    '10-06' => ['Arthaud', 'Bruno', 'Foy', 'Marie-Françoise', 'Marie-Rose'],
    '10-07' => ['Auguste', 'Serge'],
    '10-08' => ['Pélagie', 'Thaïs'],
    '10-09' => ['Abraham', 'Denis', 'Ghislain', 'Sibylle'],
    '10-10' => ['Clair', 'Hugolin'],
    '10-11' => ['Emmanuelle', 'Firmin', 'Soledad'],
    '10-12' => ['Edwin', 'Félix', 'Wilfrid'],
    '10-13' => ['Fauste', 'Géraud'],
    '10-14' => ['Calixte', 'Céleste'],
    '10-15' => ['Aurélie', 'Sévère', 'Thérèse'],
    '10-16' => ['Gaudéric', 'Hedwige', 'Marguerite', 'Marguerite-Marie'],
    '10-17' => ['Baudouin', 'Ignace'],
    '10-18' => ['Luc'],
    '10-19' => ['Isaac', 'Jogues', 'René'],
    '10-20' => ['Adeline'],
    '10-21' => ['Céline', 'Ursule'],
    '10-22' => ['Elodie', 'Jean-Paul'],
    '10-23' => ['Domice', 'Ode'],
    '10-24' => ['Florentin', 'Magloire'],
    '10-25' => ['Chély', 'Crépin', 'Hilaire'],
    '10-26' => ['Cédric', 'Démétrius', 'Dimitri'],
    '10-27' => ['Antoinette', 'Emeline'],
    '10-28' => ['Dimitri', 'Jude', 'Simon', 'Thaddée'],
    '10-29' => ['Chiara', 'Honorat', 'Narcisse'],
    '10-30' => ['Bienvenue'],
    '10-31' => ['Alphonse', 'Quentin'],
    '11-01' => ['Bénigne', 'Tous les prénoms', 'Toussaint'],
    '11-02' => ['Marcien', 'Victorin'],
    '11-03' => ['Abigaël', 'Gwenaël', 'Gwendal', 'Hubert', 'Sylvie'],
    '11-04' => ['Charles', 'Emeric', 'Flour', 'Vital'],
    '11-05' => ['Bertille', 'Kerrien', 'Sylvie'],
    '11-06' => ['Léonard', 'Melaine', 'Théobald', 'Winnoc'],
    '11-07' => ['Engelbert', 'Ernest', 'Hercule', 'Karine'],
    '11-08' => ['Geoffroy', 'Willehad'],
    '11-09' => ['Nectaire', 'Théodore', 'Ursin'],
    '11-10' => ['Démétrien', 'Japhet', 'Juste', 'Léon', 'Nausicaa', 'Noé'],
    '11-11' => ['Mahine', 'Marine', 'Martin', 'Ménas', 'Véran'],
    '11-12' => ['Christian', 'Diego', 'Emilien', 'Josaphat'],
    '11-13' => ['Abbon', 'Brice', 'Maxellende'],
    '11-14' => ['Grégoire', 'Laurent', 'Sidoine'],
    '11-15' => ['Albert', 'Léopold', 'Maclou', 'Malo', 'Sidoine', 'Victoire'],
    '11-16' => ['Edmond', 'Emilion', 'Gertrude', 'Marguerite'],
    '11-17' => ['Aignan', 'Elisabeth', 'Hilda', 'Loëlise', 'Salomé'],
    '11-18' => ['Aude', 'Odon', 'Philippine'],
    '11-19' => ['Eudes', 'Haude', 'Mechtilde', 'Tanguy'],
    '11-20' => ['Bernward', 'Edmond', 'Octave'],
    '11-21' => ['Dimitri', 'Gélase', 'Rufus'],
    '11-22' => ['Cécile', 'Céline', 'Philémon', 'Selah'],
    '11-23' => ['Clément', 'Colomban', 'Séverin'],
    '11-24' => ['Flora', 'Kenan'],
    '11-25' => ['Béatrice', 'Catherine'],
    '11-26' => ['Conrad', 'Delphine', 'Innocent'],
    '11-27' => ['Virgile'],
    '11-28' => ['Catherine', 'Quiéta'],
    '11-29' => ['Saturnin', 'Sernin'],
    '11-30' => ['André', 'Maxence'],

    '12-01' => ['Eloi', 'Florence', 'Rondro'],
    '12-02' => ['Bibiane', 'Jan', 'Jesse', 'Silvère'],
    '12-03' => ['Attala', 'François-Xavier', 'Galgano', 'Sophonie'],
    '12-04' => ['Ada', 'Barbara', 'Barbe', 'Cyran', 'Meadow', 'Osmond', 'Solal', 'Solick'],
    '12-05' => ['Bassus', 'Crispine', 'Gérald', 'Sabas'],
    '12-06' => ['Colette', 'Nicolas'],
    '12-07' => ['Ambroise', 'Khalid'],
    '12-08' => ['Azucena', 'Concepción', 'Immacolata', 'Macaire', 'Romaric', 'Thibaud'],
    '12-09' => ['Gorgonie', 'Léocadie'],
    '12-10' => ['Eulalie', 'Lorette'],
    '12-11' => ['Arthur', 'Damase', 'Daniel', 'Sabin'],
    '12-12' => ['Alfred', 'Corentin', 'Guadalupe'],
    '12-13' => ['Josse', 'Josserand', 'Lucie'],
    '12-14' => ['Arès', 'Eutropie', 'Fortunat', 'Nicaise', 'Odile', 'Venance'],
    '12-15' => ['Nino', 'Victoire', 'Virginie'],
    '12-16' => ['Adélaïde', 'Alizée'],
    '12-17' => ['Briac', 'Daniel', 'Gaël', 'Judicaël'],
    '12-18' => ['Gatien', 'Wynnebald'],
    '12-19' => ['Anastase', 'Darius', 'Théa', 'Urbain'],
    '12-20' => ['Isaac', 'Jacob', 'Zéphyrin'],
    '12-21' => ['Pierre'],
    '12-22' => ['Adam', 'Françoise-Xavière', 'Xavière'],
    '12-23' => ['Armand', 'Thorlak'],
    '12-24' => ['Adèle', 'Noémie'],
    '12-25' => ['Belén', 'Emmanuel', 'Jesus', 'Noël'],
    '12-26' => ['Etienne'],
    '12-27' => ['Fabiola', 'Jean'],
    '12-28' => ['Gaspard', 'Innocent'],
    '12-29' => ['Abigaël', 'David', 'Eloha'],
    '12-30' => ['Roger'],
    '12-31' => ['François-Régis', 'Jean-François', 'Régis', 'Sylvestre'],
];


// === 3. Création du tableau enrichi ===
$prenoms_enrichis = [];
$totalOccurence = 0;

foreach ($prenoms_complet as $date => $prenoms) {
    $details = [];
    foreach ($prenoms as $prenom) {
        $prenomKey = mb_strtoupper ($prenom);
        if (isset($frequences[$prenomKey])) {
          $occurrence = $frequences[$prenomKey];
          $totalOccurence = $totalOccurence + $occurrence;
        } else {
          print("$prenom -> $prenomKey is not found \n");
          $occurrence = 0;
        }

        $details[] = [
            'prenom' => $prenom,
            'occurrence' => $occurrence
        ];
    }
    // Tri décroissant par occurrence
    usort($details, function($a, $b) {
        return $b['occurrence'] <=> $a['occurrence'];
    });

    $prenoms_enrichis[$date] = $details;
}

// === 4. Écriture dans un fichier PHP ===
$fichierSortie = 'export.php';
$contenu =  "<?php\n\n/* This file is part of Jeedom.\n *\n * Jeedom is free software: you can redistribute it and/or modify\n * it under the terms of the GNU General Public License as published by\n * the Free Software Foundation, either version 3 of the License, or\n * (at your option) any later version.\n *\n * Jeedom is distributed in the hope that it will be useful,\n * but WITHOUT ANY WARRANTY; without even the implied warranty of\n * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n * GNU General Public License for more details.\n *\n * You should have received a copy of the GNU General Public License\n * along with Jeedom. If not, see <http://www.gnu.org/licenses/>.\n */\n\n";
$contenu .= "global \$DOMOGEEK_FEAST;\n\$DOMOGEEK_FEAST = " . var_export($prenoms_enrichis, true) . ";\n";

file_put_contents($fichierSortie, $contenu);

echo "✅ Fichier '$fichierSortie' créé avec succès.\n";

//print_r($prenoms_enrichis);
?>
